### PR TITLE
Added wasamasa and abo-abo.

### PR DESCRIPTION
**Pull request by WolfeCub**

### CODE REVIEW

**Comment by tarsius** [comment]
Two maintainers who definitely deserve to be added! Do they not have any donation pages yet?

**Comment by WolfeCub** [comment]
I haven't been able to find a donation page for either.

**Comment by tarsius** [comment]
Well, lets ask them. @wasamama @abo-abo, do you accept donations?

**Comment by WolfeCub** [comment]
@wasamasa 

I mistyped my commit message.

**Comment by tarsius** [comment]
... and I blindly copy-pasted :wink:

**Comment by abo-abo** [comment]
@tarsius I haven't set up any donation pages so far. Mostly because I wasn't expecting any amount of money that would make the trouble of setting it up worthwhile.

But looking at the success of the Magit campaign, and my recently changed work circumstances, I'm considering setting up a Patreon page. If I could earn enough to hack on Free Software one day per week, that would be totally awesome. Congratulations on your success, by the way. I'm sure you'll do great. And have fun!

**Comment by tarsius** [comment]
> If I could earn enough to hack on Free Software one day per week, that would be totally awesome.

Indeed! For you in particular, but for the community too. I very much like your packages because they go that "tiny" step further that gives them personality. I definitely want more of that and I am sure there are many users who feel the same way.

@purcell also didn't have a Patreon page until a week ago and now he is already at $61. Not very much but still. I think all the "marketing" that has happened so far is that I tweeted about it, so there is still a lot of room for growth. My own Patreon page (and similar) saw a big growth in 2017 (and I think the same is the case for those of other elisp maintainers as well). Still, what my Kickstarter has thought me is that you do have to ask -- more than one user said "I don't like Kickstarter, have you considered something like Patreon?" even though that was available and prominently linked for years.

**Comment by wasamasa** [comment]
I don't accept donations for a few reasons:

- [This piece](http://lucumr.pocoo.org/2014/11/2/payments-in-the-future/) is very relatable to me because Germany isn't too different from Austria in this regard, donations would make tax declarations a major headache.  Compare with odd jobs where I do some small task for someone and accept a payment.
- Donations create expectations.  While I do not want to generalize, people do expect something to happen if they donate and if nothing happens, I can't blame them for getting angry over their money going seemingly nowhere.  The opposite of this is people accepting donations and spending them for non-project-related things, like booze.
- I have a full-time job doing software development, open-source is something I do because something itches me hard enough or because I've found something fun to hack on.  Maintainership is far less fun to me and involves a good deal of non-programming tasks, such as coordination with other people who are as busy as yourself and doing all those tricky decisions where you can't please everybody or can't predict how they'll turn out.  If you've checked, my GitHub activity revolves around a few projects at a time, with most of them being inactive.  I don't see how adding donations will improve this.  While you may argue that money motivates people, it doesn't magically make otherwise less fun tasks fun again or give people time to work on them.
- Somewhat related to the previous point, assuming I'd reel in as many donations as @tarsius or any other dev who did a successful kickstarter/indiegogo/... campaign, I don't see how I could make full use of it without impacting my career.  While my employer happens to be a very reasonable person I could probably work something out with, I would definitely not do something like stop being employed for a whole year and leave that hole on my CV.  The other problem I see with this is the self-organization part and motivation, but those aren't nearly as problematic.
- Assuming I fully went towards sustaining my living from donations (yay, survivorship bias) I wouldn't want to do the constant marketing to keep that cash flow.  Begging for money just feels wrong to me.
- Finally, compare my contributions with the others on the list.  The most critical thing I work on is Evil which as you can see... merely receives a few comments on in-coming bugs/PRs a week from me. I bemoan lots of things, talk a lot about how things could be done differently, yet my output is negligible.  It makes for fun conversation at conferences and the hackerspace, but if you want to donate where it matters, please pick someone else.  If you want to help me, I accept code, ideas and other digital goods (like faulty EPUBs for nov.el).  Thank you.

**Comment by Fuco1** [comment]
> I would definitely not do something like stop being employed for a whole year and leave that hole on my CV

@wasamasa I don't know about German customs but if I were interviewing someone who hacked on an opensource project while being backed by 55 thousand swiss franks from people all over the world I would just hire them and that's it.  I don't think anyone would ever look at "a hole" like that with any sort of negativity.  Just going off-topic off-topic here I suppose. :D

**Comment by tarsius** [comment]
@wasamasa Thanks for explaining why you can't accept contributions. Perfectly reasonable in my opinion.

I am wondering if we should also maintain a list of maintainers who have made that decision. For now I am keeping a private list.

I have also decided to only add maintainers to the main list for whom at least one donation option is known, or if that person him-/herself adds the entry and explicitly states that donations should go to some charity instead, as  @tzz [has done](https://github.com/tarsius/elisp-maintainers/pull/9/commits/d8e123a1e08ffb1fc8d2f126b15f4fa2bd1d5ee5).

**Comment by tarsius** [comment]
I am closing this then.

@abo-abo please open a new pr once you have setup something.

**Comment by tzz** [comment]
@tarsius I'd send something to emacs-devel and collect the responses, since there's some subset of those developers that won't or can't use GitHub.

**Comment by tarsius** [comment]
Thanks @tzz!

**Pull request closed without merging**
