### PR TITLE
Add that ein maintainer guy.

### PR DESCRIPTION
**Pull request by millejoh**

### CODE REVIEW

**Comment by purcell** [comment]
Thanks. Please add yourself in alphabetical order, though. :-)

**Comment by millejoh** [comment]
Yes, and I see now that was clearly stated in the instructions. Sigh.

Alphabetical on first or last name? Looks like first, but I don't trust myself at the moment.

**Comment by tarsius** [comment]
By first name (or whatever name you put first (not everyone actually has  a first name)).

**Comment by tarsius** [comment]
Thanks!

**Pull request merged**
