### PR TITLE
Improve networking

### PR DESCRIPTION
**Pull request by AdamNiederer**
Hello,

These are all of the top-level projects of which I consider myself the active, primary maintainer. I don't have any monetary links for now, though.

### CODE REVIEW

**Comment by tarsius** [comment]
Please move your entry to the beginning (the list is sorted alphabetically).

I'll probably delay merging this until you have a donation option.

**Comment by tarsius** [comment]
I've decided to only add entries that have at least one donation option (or "donate to some charity instead") for the time being. I'll leave this pr open for a while so that you can easily update it.

**Comment by AdamNiederer** [comment]
There doesn't appear to be a particularly attractive way to accept donations, so I'll redirect people to the SFC and EFF for the time being.

**Comment by tarsius** [comment]
Sorry this took me so long.

**Pull request merged**
